== Python Development Packaging
In the Python ecosystem, there are two kinds of packages, development and distribution. 
This section will focus on development packages, as distribution is outside of the scope for this package. 
Here are some options for dealing with these kinds of packages. The current recommendation is to use pip packaging for vanilla python and any c extensions and any packages that integrate with LSST stack will use EUPS as per DM standards.

=== PIP
This is the defacto standard for python packages.
Packages are created using the setup.py format which uses setuptools as the backend device. 
This is the default way for python packages to be installed. 
Setuptools can handle python c extensions and other such steps. 
PIP uses warehouse as its public distribution server but there are self-hosted options

=== Conda
This is an alternative package system that was designed for scientific python use. 
Essentially meant to make installing complex python libraries like scipy, astropy and nltk easier to install on different OSs. 
It can build more than python packages and has a distribution mechanism in place. It has a public option for allowing anyone to install its packages. 
It also has private repos available to organizations that cost money. 
Cost is unclear. 
Conda also has a self-hosted enterprise version which also costs money but price is unknown. 
It essentially can distribute any tool that can be installed and setup using shell commands(build tools included). 
Conda documentation is located link:https://conda.io/docs/[here].

* Could be used to handle EUPS packages underneath the conda environment. 

=== EUPS
This is the packaging system used by LSST's DM and forms the backend to the stack,which has a design philosophy that uses environment modules to build packages. 
Each package is built using an scons-lsst recipe which allows for flexibility regarding packages that are polylingual. 
Several of TSSW's packages have stipulations which require the use of EUPS. 
DM's documentation on the matter is located link:https://developer.lsst.io/stack/eups-tutorial.html[here]. 
The EUPS source code is located link:https://github.com/RobertLuptonTheGood/eups[here]. 
That link also includes installation instructions outside of the LSST stack.